---
title: "Assignment 4"
author: "Claudia Flores"
date: "3/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


```{r}
### Function 

## Create a function that takes a vector and find the most common fish, the rarest fish, the total number of fish, and has the option to plot a histogram of the number of each fish type, with a title giving the total number of fish caught

# f = vector to factor results
# c = most common fish in factor string
# l = least common fish in factor string
# t = total number of fish in factor string
# p = variable to hold histogram plot

fish_summary <- function(name_vec, graph = FALSE){
  # Body 
  f <- as.factor(name_vec)
  c <- names(which.max(summary(f)))
  l <- names(which.min(summary(f)))
  t <- sum(summary(f))
  plottitle = sprintf("We mostly caught %s \n max catch(%s)", 
                      names(which.max(summary(name_vec))), 
                      max(summary(name_vec)))
  p <- if(graph == TRUE) 
    return((ggplot(data.frame(name_vec=name_vec), 
                   aes(name_vec, fill=name_vec)) + 
              geom_histogram(stat="count")+
              labs(title = plottitle,x = "Fish Type", y = "Count of Fish Type")))

  values <- list(c,l,t,p)
  return(values)
}


### Data

## Read in file 'fish.txt' data
fish_data <- read.delim("fish.txt")

## Change fish_data data frame into a vector
fish_data <- as.vector(fish_data$x)

### Example 

## Run fish_summary() function with 'fish.txt' file
fish_summary(fish_data, graph = TRUE)
```
Final Submission
```{r}
#' fish_summary
#' 
#' The function takes a vector and find the most common fish, the rarest fish, the total number of fish, and has the option to plot a histogram of the number of each fish type.
#' @param name_vec vector of fish names
#' @param graph histogram with count of fish types (default = FALSE)
#' @return Total number of fish = t, Most common fish = c, Rarest fish = l, Histogram with count of fish types = p
#' @author Claudia Flores & Mariano Viz


fish_summary <- function(name_vec, graph = FALSE) {
  
  f <- as.factor(name_vec) #convert vector to factor class
  c <- names(which.max(summary(f))) #get the name of the most common fish
  l <- names(which.min(summary(f))) #get the name of the least common fish
  t <- sum(summary(f)) #get the total number of fish
  
 
  if(graph == TRUE) {
    #Plot title showing  total number, and most and least common fish
    plottitle = sprintf("Total number of fish: %s", t)
    
    #Histogram with count of fish types
    p <- ggplot(data.frame(name_vec=name_vec), 
                aes(name_vec, fill=name_vec)) + 
      geom_histogram(stat="count", 
                     show.legend = FALSE)+
      labs(title = plottitle,x = "Fish Type", y = "Count") +
      theme_minimal()
    
    
    values <- list( sprintf("Total number of fish: %s", t), 
                    sprintf("Most common fish: %s ", c), 
                    sprintf("Rarest fish: %s", l), p 
    )
    
  } else
    
    values <- list(sprintf("Total number of fish: %s", t), 
                  sprintf("Most common fish: %s ", c), 
                  sprintf("Rarest fish: %s", l)) 
  
  return(values)
}

## Read in file 'fish.txt' data
fish_data <- read.delim("fish.txt")

## Change fish_data data frame into a vector
fish_data <- as.vector(fish_data$x)

## Run fish_summary() function with 'fish.txt' file
fish_summary(fish_data)


fish_summary(fish_data, graph = TRUE)
```




