---
title: "Assignment 3"
author: "Claudia Flores"
date: "2/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

case_when
```{r}
### Function 

## Create a function for flood recurrence interval probability
# Function finds the probability in any given year that a flood of that magnitude will be equaled or exceeded 

# Y = years in records
# T = recurrence interval (note: not an independent input, but a dependent input)
# R = magnitude ranking

recurrence_interval_prob <- function(Y,R){
  # Body 
  T <- Y + 1
  Prob <- (1)/(T/R)
  # Error checking
  R = ifelse((R < 0), 
             return("Ranking must be a positive integer"), 
             R)
  # Output is the probability 
  risk <- case_when( # Print the following "" if certain conditions (e.g. <,>,=...) for Prob results are met
             Prob > 0.5 ~ "High",
             Prob == 0.5 ~ "Medium",
             Prob < 0.5 ~ "Low"
             )
  return(risk)
}

# Source the recurrence_interval_prob.R function
source("../R/recurrence_interval_prob.R")

# Example fo years in records = 41 and Magnitude Ranking = 1

recurrence_interval_prob(41,1)
```

WARNING: another case_when example using it outside the function 
```{r}
######################## Tried another way to do case_when outside of the function ########################

### Data Frame

## Create a data frame to run your function using a loop and name four columns: R, Maximum Annual Discharge m^3/s, Year, and Y 

ranks = data.frame(R = c(1,2,3,4,5,6,7,8,9,10), # Ranking magnitude
                   maximum_annual_discharge_m3_s = c(507,453,343,323,300,299,275,260,100,50),
                   year = c(2010,1975,1990,2004,2013,2006,1993,1991,1996,1999),
                   Y = (10) # Years on record
                   )

## Create a data frame to put probability results from loop
results = as.data.frame(matrix
                          (nrow = length(ranks), # Number of rows
                            ncol= 1) # Number of columns
                          )

### Loop

## Run a loop through the R and Y columns in the ranks data frame created to get probability results
for (i in 1:nrow(ranks)) # For each value (i) in the rows under the rank column
  {
  results[i,1] = # Place the result for each value (i) in the results data frame in column 1
    recurrence_interval_prob( # Function
      Y=ranks$Y[i], # Use values in the ranks data frame column Y
      R=ranks$R[i] # Use values in the ranks data frame column R
              )
}

## Name your column where your probability results are to "Prob"
names(results)[1] <- "Prob"


### Case_when 

## Add a column for results of the probability risk and use case_when to determine what the probability risk is based on the parameters of Prob > 0.5 is high, Prob = 0.5 is medium, and Prob < 0.5 is low
results <- results %>% 
  mutate(Prob_Risk = # Name of new column
           case_when( # Print the following "" if certain conditions for Prob results are met
             results$Prob > 0.5 ~ "High",
             results$Prob == 0.5 ~ "Medium",
             results$Prob < 0.5 ~ "Low"
             )
         )

```


while loop
```{r}
### Function 

## Create a function for the amount of rebate a household will receive for removing turf from their irrigated space
# Function finds the amount of rebate received

# sq_ft = amount of turf removed in sq_ft 
# rebate_price = USD rebate price for each sq_ft removal of turf 

rebate_turf_removal <- function(sq_ft,rebate_price = 2.13){
  # Error checking
  sq_ft = ifelse((sq_ft < 0), # Sq-ft has to be greater than zero to receive any kind of rebate
               return("Did you remove all the turf already?"), 
               sq_ft)
  # Body 
  total_rebate <- sq_ft * rebate_price
  # Output is rebate received for turf removal in USD
  return(total_rebate)
}

# Source the rebate_turf_removal.R function
source("../R/rebate_turf_removal.R")

### While loop

## Set up initial conditions to run loop

sq_ft = 0 # loop will begin with square feet as zero so in the equation it starts at one
rebate_price = 2.13 # this is the rebate price for every sq_ft removal of turf
total_rebate = 0 # loop will start off with the total rebate given as zero
  
# How much sq ft of turf from my 900 sq ft yard do I need to remove to receive at least 500 USD?
while((total_rebate <= 500) & (sq_ft <= 900)) # run loop until at least 500 dollars of rebate is received and must be equal to or less than the total amount of turf that can actually be removed
  {
  sq_ft = 1 + sq_ft # to loop through sq_ft values
  total_rebate = rebate_turf_removal(sq_ft, rebate_price) # function to determine total rebate received
 
}

# Amount of sq ft needed to be removed to receive at least 500 USD worth of rebate
print(sq_ft)
```

